apiVersion: v1
kind: Pod
metadata:
  name: alpine
spec:
  containers:
  - image: alpine:latest
    command: ["sh", "-c"]
    args: ["sleep 3600"]
    imagePullPolicy: IfNotPresent
    name: alpine
  serviceAccountName: app-robot-user
  restartPolicy: Always
